### PR TITLE
Add retrain script

### PR DESCRIPTION
**Pull request by fanshi14**
- add option to save all checkpoint (actor architecture, distribution, critic architecture, optimizer)
- add script to retrain based on previous checkpoint

### CODE REVIEW

**Comment by fanshi14** [comment]
I wonder if it's better to add option whether to save policy_xx.txt file.
Because it is large (~500k) and not very useful since you already have .pt file.

**Comment by jhwangbo** [comment]
fanshi, I don't get why we need a separate file for retraining. It should be just one if statement in the beginning which initialize policy parameters.

**Comment by fanshi14** [comment]
Do you mean the retraining function should be integrated inside ```runner.py```?
I agree, just tried to minimize the influence to your previous codes.

If you think it's ok, I will make a new commit to integrate them together.

**Comment by jhwangbo** [comment]
yes, that will be great. You don't have to change so much. Just a couple of lines to initialize the policy and value network parameters.

**Comment by fanshi14** [comment]
Done.
Through ```touch.save```, my codes give option to save the full checkpoint file to fully record 

- policy architecture and distribution
- critic architecture
- optimizer parameters 

In retrain mode, ```touch.load``` all these parameters.

I wonder whether this method fits your idea.

**Comment by jhwangbo** [comment]
Hi Fanshi, what is full_XXX.pt file? I get an error when I tried to retrain a policy

`FileNotFoundError: [Errno 2] No such file or directory: '/home/jemin/workspace/raisimlib/raisimGymTorch/data/roughTerrain/2020-12-18-10-31-40/full_200.pt'`

**Comment by fanshi14** [comment]
> Hi Fanshi, what is full_XXX.pt file? I get an error when I tried to retrain a policy

As the README said, you need set ```save_all_checkpoints``` to be True, and run your runner.py to generate full checkpoint (full_xx.pt), then you could use it for retrain.

**Comment by jhwangbo** [comment]
great, it works. I removed ``save_all_checkpoints`` and made the runner file save the full checkpoints all the time.

**Comment by jhwangbo** [comment]
fanshi, is there a reason that you copy the pre-trained model? This will be saved again in the beginning when it evaluates the initial policy.

**Comment by fanshi14** [comment]
yes, the reason is more convenience to debug, in which the user could locate the exact pre-trained model more clearly.
The cost is just wasting a tiny disk volume to copy it.

**Comment by jhwangbo** [comment]
make sense. Thx for the prompt response

**Pull request merged**
